version: '3.9'
services:
  api:
    env_file:
      - ./.env
    image: rxcrud/api:1.0
    restart: on-failure
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5002:80
      - 5003:443
    volumes:
      - ./certificate:/app/certificate
      - ./temp-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ConnectionStrings__DefaultConnection=Host=10.0.0.131;Port=5432;Database=RXCrud;Username=postgres;Password=1234;
      - Kestrel__Certificates__Default__Password=1234
      - Kestrel__Certificates__Default__Path=/app/certificate/certificate.pfx
    networks:
      - rxcrud_net

  web:
    image: rxcrud/web:1.0.0
    restart: on-failure
    container_name: web
    depends_on:
      - api
    build:
      context: ../rxcrud-web-template
      dockerfile: Dockerfile
    ports:
      - 3001:80
    environment:
      - REACT_APP_API_URL=https://localhost:5003/
    networks:
      - rxcrud_net

networks:
  rxcrud_net:
    name: rxcrud_net